# Generated by Django 4.2 on 2023-04-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='for_deleting',
            field=models.BooleanField(default=False, verbose_name='На удаление'),
        ),
    ]
