# Generated by Django 4.2 on 2023-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_document_for_deleting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(help_text='Содержание', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='for_deleting',
            field=models.BooleanField(default=False, help_text='Пометить на удаление', verbose_name='На удаление'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(help_text='Наименование', max_length=100, verbose_name='Наименование'),
        ),
    ]
